/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { app_version$_T } from './app_version$_b'
import type { app_version_query$_T } from './app_version_query$_b'
export interface app_version_ctx_I {
	app_version$?:app_version$_T
	app_version_query$?:app_version_query$_T
}